// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyuxvxqxpxxfgcgfntyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5dXh2eHF4cHh4ZmdjZ2ZudHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MTg0NDcsImV4cCI6MjA1ODE5NDQ0N30.AriqyF-L1r_Nz9KFIaAw57nQDP_gLrdWccnfl37SRjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);